[package]
name = "ratelimiter"
version = "0.1.0"
authors = ["Sudarsan <sudar.theone@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
